spring:
  datasource:
    global-cloud:
      url: jdbc:mysql://localhost:3306/summer_vivo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
      username: root
      password: bbk@123456
      driver-class-name: com.mysql.jdbc.Driver
    global-tool:
        url: jdbc:mysql://localhost:3306/summer_vivo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
        username: root
        password: bbk@123456
        driver-class-name: com.mysql.jdbc.Driver
    ws-future:
      IDVIVO:
        url: jdbc:mysql://localhost:3306/summer_vivo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
        username: root
        password: bbk@123456
        driver-class-name: com.mysql.jdbc.Driver
    summer-basic:
      IDVIVO:
        url: jdbc:mysql://localhost:3306/summer_vivo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
        username: root
        password: bbk@123456
        driver-class-name: com.mysql.jdbc.Driver
    summer-general:
        url: jdbc:mysql://localhost:3306/summer_vivo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
        username: root
        password: bbk@123456
        driver-class-name: com.mysql.jdbc.Driver
    kingdee:
      IDVIVO:
        url: jdbc:sqlserver://localhost:1433;DatabaseName=AIS20161016114758
        username: sa
        password: bbk@123456
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    factory:
      IDVIVO:
        url: jdbc:jtds:sqlserver://id-transfer.vivo.xyz/PlantESaleWeb
        username: user_m13e00
        password: user_m13e00
        driver-class-name: net.sourceforge.jtds.jdbc.Driver
  redis:
    host: localhost
    password:
    port: 6379
    database: 0
    max-idle: 100
    max-total: 200
companyNames: IDVIVO