spring:
  http:
    multipart:
      maxFileSize:  100Mb # Max file size.
      maxRequestSize: 100Mb # Max request size.

management:
  security:
    enabled: false

logging:
  file: summer-gateway.log
  level:
    org.springframework.cloud: DEBUG
    org.springframework.security: DEBUG
    net.myspring: DEBUG
zuul:
  routes:
    webapp:
      path: /**
      url: http://localhost:8888
    summer-uaa:
      path: /user/**
      url: http://localhost:1100/uaa/user
    summer-basic: /api/basic/**
    summer-general: /api/general/**
    ws-future: /api/ws/future/**
    global-tool: /api/global/tool/**
    global-cloud: /api/global/cloud/**
  host:
    socket-timeout-millis: 18000
    connect-timeout-millis: 18000
    max-total-connections: 200
  add-proxy-headers: true
  semaphore:
    max-semaphores: 2000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

hystrix:
  command:
    default:
      circuitBreaker:
        forceClosed :  true
      execution:
        timeout:
          enabled: false
        isolation:
          semaphore:
            maxConcurrentRequests: 2000
          thread:
            timeoutInMilliseconds: 10000

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:1100/uaa/oauth/token
      userAuthorizationUri: http://localhost:1100/uaa/oauth/authorize
      clientId: ui
      clientSecret: password
    resource:
      preferTokenInfo: false
      user-info-uri: http://localhost:1100/uaa/user