spring:
  session:
    store-type: redis
    timeout: 5
management:
  security:
    enabled: false
server:
  # Use different context-path to avoid session cookie overlapping
  context-path: /uaa

feign:
  hystrix:
    enabled: false
  httpclient:
    enabled: true


setting:
    adminIdList:  1

logging:
  file: summer-uaa.log