spring:
  application:
    name: summer-uaa
server:
  port: 9999
  # Use different context-path to avoid session cookie overlapping
  context-path: /uaa
  use-forward-headers: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://168.192.1.20:1000/eureka/