spring:
  application:
    name: summer-uaa
  datasource:
    url: jdbc:mysql://168.192.1.243:3306/db_id_vivo_hr
    username: root
    password: bbk@123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  config-location: classpath:/mybatis-config.xml
server:
  port: 1100
  # Use different context-path to avoid session cookie overlapping
  context-path: /uaa
  use-forward-headers: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/