spring:
  application:
    name: global-cloud
  profiles:
    active: dev
server:
  port: 2000
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

security:
  oauth2:
    client:
      clientId: cloud-service
      clientSecret: cloud-password
      accessTokenUri: http://localhost:1100/uaa/oauth/token
      userAuthorizationUri: http://localhost:1100/uaa/oauth/authorize
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:1100/uaa/user
feign:
  hystrix:
    enabled: false

ribbon:
  ReadTimeout: 180000
  ConnectTimeout: 180000
logging:
  file: global-cloud.log
  level:
    org.springframework.cloud: DEBUG
    org.springframework.security: DEBUG
    net.myspring: DEBUG
