spring:
  application:
    name: global-cloud
  datasource:
    url: jdbc:mysql://168.192.1.17:3316/db_oppo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: bbk@123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    password:
    port: 6379
    database: 0
    max-idle: 25
    max-total: 50

server:
  port: 2000
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

security:
  oauth2:
    client:
      clientId: cloud-service
      clientSecret: cloud-password
      accessTokenUri: http://localhost:1100/uaa/oauth/token
      userAuthorizationUri: http://localhost:1100/uaa/oauth/authorize
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:1100/uaa/user