server:
  port: 9900

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: http://ncoppo.com:66/liuj/summer.git
          search-paths: config-repo
          username: config
          password: configconfig