spring:
  application:
    name: summer-gateway
  profiles:
    active: dev
management:
  security:
    enabled: false

server:
  port: 443
  ssl:
    key-store: classpath:hi.ncoppo.com.jks
    key-store-password: 882421615w0f
  http:
    port : 1200

logging:
  file: summer-gateway.log
  level: debug

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
zuul:
  routes:
    webapp:
      path: /**
      url: http://localhost:8888
    summer-uaa:
      path: /user/**
      url: http://localhost:1100/uaa/user
    summer-basic: /api/basic/**
    summer-general: /api/general/**
    ws-future: /api/ws/future/**
    global-tool: /api/global/tool/**
    global-cloud: /api/global/cloud/**
  host:
    socket-timeout-millis: 180000
    connect-timeout-millis: 180000
    max-total-connections: 200
  add-proxy-headers: true
  semaphore:
    max-semaphores: 2000

ribbon:
  ReadTimeout: 180000
  ConnectTimeout: 180000

hystrix:
  command:
    default:
      circuitBreaker:
        enabled:  false
      execution:
        timeout:
          enabled: false
        isolation:
          semaphore:
            maxConcurrentRequests: 2000
          thread:
            timeoutInMilliseconds: 180000

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:1100/uaa/oauth/token
      userAuthorizationUri: http://localhost:1100/uaa/oauth/authorize
      clientId: ui
      clientSecret: password
    resource:
      preferTokenInfo: false
      user-info-uri: http://localhost:1100/uaa/user