spring:
  application:
    name: summer-gateway
server:
  port: 3333
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
zuul:
  routes:
    summer-uaa:
      sensitiveHeaders:
      path: /uaa/**
      stripPrefix: false
    summer-hr: /hr/**
  add-proxy-headers: true