spring:
  redis:
    host: localhost
    password:
    port: 6379
    database: 0
    max-idle: 25
    max-total: 50
  application:
    name: summer-gateway
server:
  port: 1200
management:
  security:
    enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
zuul:
  routes:
    webapp:
      path: /**
      url: http://localhost:8888
    summer-uaa:
      path: /user/**
      url: http://localhost:1100/uaa/user
    summer-basic: /api/basic/**
    summer-general: /api/general/**
    ws-future: /api/ws/future/**
    global-tool: /api/global/tool/**
    global-cloud: /api/global/cloud/**
  host:
    socket-timeout-millis: 1000000
    connect-timeout-millis: 1000000
  add-proxy-headers: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 1000000

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000


security:
  oauth2:
    client:
      accessTokenUri: http://localhost:1100/uaa/oauth/token
      userAuthorizationUri: http://localhost:1100/uaa/oauth/authorize
      clientId: ui
      clientSecret: password
    resource:
      preferTokenInfo: false
      user-info-uri: http://localhost:1100/uaa/user
  sessions: ALWAYS

setting:
    adminIdList:  1

logging:
  file: summer-gateway.log