spring:
  application:
    name: summer-gateway
server:
  port: 3333
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
zuul:
  routes:
   summer-uaa:
     path: /uaa/**
   summer-hr:
     path: /hr/**